config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  ActiveAdmin.routes(self)
  devise_for :users

    get '/movies/:id/partial', to: 'movies#partial'
    get '/movies/newest', to: 'movies#newest'
    get '/movies/highrated', to: 'movies#highrated'
    get '/movies/pending', to: 'movies#pending'
    get '/movies/pending/approve', to: 'reviews#approve'
    get '/home', to: 'home#home'
    get "/movies/#{Time.now.year}", to: 'movies#top10'
    get '/movies/alphabetical', to: 'movies#alphabetical'
    get '/movies/rated', to: 'movies#rated'
    get '/movies/most-reviewed', to: 'movies#most_reviewed'
    get '/results', to: 'movies#results'
    get '/movies/custom_new', to: 'movies#custom_new'
    post '/movies/custom_create', to: 'movies#custom_create'
    get '/thankyou', to: 'home#thankyou'
    get '/select', to: 'movies#select'

    resources :profiles

    resources :movies do
      resources :reviews do
        resources :review_ratings, only: [:create, :new, :edit, :update]
      end
    end
  root to: 'movies#newest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_user
  before_action :find_profile, only: [:update]

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.create(profile_params)
    current_user.profile = @profile
    current_user.save!
    authorize @profile
    redirect_to profiles_path(@profile)
  end

  def edit
    @profile = current_user.profile
    current_user.email = params[:email] if params[:email]
    authorize @profile
  end

  def update
    @profile.update(profile_params)
    @profile.save!
    current_user.profile = @profile
    current_user.save!
    authorize @profile
    redirect_to profiles_path(@profile)
  end

  def destroy
    @profile = current_user.profile
    @profile.destroy!
    redirect_to movies_path
  end

  def index
    @profile = current_user.profile
    @reviews = @profile.user.reviews.newest
    policy_scope(@profile)
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :first_name, :last_name, :info, :country)
  end

  def find_user
    @user = current_user
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= form_for (@profile) do |f| %>
      <div class="row">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control input-lg edit-input title-form"%>
      </div>
      <div class="row">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :country %>
        <%= f.text_field :country, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :info %>
        <%= f.text_area :info, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
      <div class="col-sm-6 sm-offset-6">
        <%= f.submit class: 'btn vegan-btn' %>
        <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-6 col-xs-12">
      <div class="portfoliocard ">
        <div class="coverphoto"></div>
        <div class="left_col">
          <div class="followers">
            <h4>
              Reviews:
            </h4>
            <div class="follow_count"><%= @profile.user.reviews.size %></div>
            Written
          </div>
          <div class="following">
            <div class="follow_count"><%= @profile.user.review_ratings.size %></div>
            Reviewed
          </div>
        </div>
        <div class="right_col">
          <h2 class="name"><%= @profile.username %></h2>
          <br><br>
          <h3 class="location"><%=  @profile.country.capitalize  %> </h3>
          <ul class="contact_information">
          <li class="work">Vegan Critic</li>
          <li class="info"> <%= @profile.first_name + " " + @profile.last_name%> </li>
          </ul>
          <%= link_to 'Edit profile', edit_profile_path(@profile), class: 'btn vegan-btn', style: "    margin-top: 10%; margin-left: 25%;" %>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-xs-12">
      <div class="profile-scrollbox">
        <% @profile.user.reviews.newest.each do |review| %>
        <div class="recent-activity">
          <%= link_to movie_review_path(review.movie, review) do %>
          <div class="product">
            <div class='product-body'>
              <h3 style="color: black;">
                <%= review.movie.title %>
              </h3>
              <%= review.approved ? "" : "Waiting for approval" %>
              <p>
                <%= review.title %> @ <%= review.created_at.strftime('%A, %d %b %Y %l:%M %p') %> has been rated <%= review.review_ratings.size %> times!
                <%= review.review_rating ? review.review_rating : 'Not rated yet' %> <div style="color: green" class='fa fa-star'></div>
              </p>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= form_for (@profile) do |f| %>
      <div class="row">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control input-lg edit-input title-form"%>
      </div>
      <div class="row">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :country %>
        <%= f.text_field :country, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
        <%= f.label :info %>
        <%= f.text_area :info, class: "form-control input-lg edit-input title-form" %>
      </div>
      <div class="row">
      <div class="col-sm-6 sm-offset-6">
        <%= f.submit "Update profile", class: 'btn vegan-btn' %>
        <% end %>
        </div>
      </div>

    </div>
  </div>
</div>