config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  ActiveAdmin.routes(self)
  devise_for :users

    get '/movies/:id/partial', to: 'movies#partial'
    get '/movies/newest', to: 'movies#newest'
    get '/movies/highrated', to: 'movies#highrated'
    get '/movies/pending', to: 'movies#pending'
    get '/movies/pending/approve', to: 'reviews#approve'
    get '/home', to: 'home#home'
    get "/movies/#{Time.now.year}", to: 'movies#top10'
    get '/movies/alphabetical', to: 'movies#alphabetical'
    get '/movies/rated', to: 'movies#rated'
    get '/movies/most-reviewed', to: 'movies#most_reviewed'
    get '/results', to: 'movies#results'
    get '/movies/custom_new', to: 'movies#custom_new'
    post '/movies/custom_create', to: 'movies#custom_create'
    get '/thankyou', to: 'home#thankyou'
    get '/select', to: 'movies#select'

    resources :profiles

    resources :movies do
      resources :reviews do
        resources :review_ratings, only: [:create, :new, :edit, :update]
      end
    end
  root to: 'movies#newest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy, :partial]
  before_action :disable_nav, only: [:partial]
  before_action :find_user, only: [:show, :pending, :index, :rated, :show,]
  skip_before_action :authenticate_user!, only: [:index, :show, :partial, :highrated, :top10, :most_reviewed, :newest, :rated]

  def index
    @active = 'newest-b'
    @movies = policy_scope(Movie).order(created_at: :desc)
    @movie = @movies[0]
    partial(@movie) if @movie
  end

  def show
    @reviews = @movie.reviews.approved.order(review_rating: :desc)
    respond_to do |format|
      format.html
      format.js {
        partial(@movie)
      }
    end
  end

  def new
    @movie = Movie.new
    authorize @movie
  end

  def create
    title = movie_params["title"]
    if @movie = Movie.find_by_title(title.strip)
      authorize @movie
      redirect_to select_path(movie_id: @movie.id)
    elsif @movie = Movie.search_movie(title)
      authorize @movie
      redirect_to select_path(movie_id: @movie.id)
    else
      authorize Movie.new
      flash[:alert] = "Could not find movie in database"
      redirect_to movies_custom_new_path
    end
  end


  def select
    @movie = Movie.find(params[:movie_id])
    authorize @movie
  end

  def custom_new
    if params[:format]
      @movie = Movie.find(params[:movie_id])
      unless @movie.reviewed?
        @movie.destroy
      end
    end
    @movie = Movie.new
    authorize @movie
  end

  def custom_create
    @movie = Movie.new(movie_params)
    @movie.title = @movie.title.strip
    @movie.save!
    authorize @movie
    redirect_to new_movie_review_path(@movie)
  end

  def edit
    @movie.title = params["title"]
  end

  def update
    @movie.update(movie_params)
    @movie.save!
    redirect_to movies_path
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  def results
    @movies = Movie.search_title(params[:title])
    authorize (Movie.first)
  end



  def top10
    # no older than september 2016
    @movies = Movie.top10
    @movie = @movies[0]
    @active = 'top10'
    partial(@movie) if @movie
    @review_rating = ReviewRating.new
    authorize (Movie.first)
    render :index
  end

  def newest
    @newest_reviews = Review.all.newest
    authorize (Movie.first)
  end

  def most_reviewed
    @active = 'most_reviewed'
    @movies = Movie.most_reviewed
    @movie = @movies[0]
    partial(@movie) if @movie
    authorize (@movie)
    render :index
  end

  def pending
    @pending_reviews = Review.unapproved
    authorize (Movie.first)
  end

  def rated
    @active = 'rated'
    @movies = Movie.by_rating.reject { |movie| movie.rating.nil? }
    @movie = @movies[0]
    partial(@movie) if @movie
    authorize (Movie.first)
    render :index
  end

  private

  def partial(movie)
    @review = movie.reviews.approved.order(review_rating: :desc).first
    @user = current_user
    if @review && current_user
      @review_rating = ReviewRating.find_by(review_id: @review.id, user_id: @user.id) || ReviewRating.new
    end
  end

  def find_user
    @user = current_user
  end

  def disable_nav
    @disable_nav = true
  end

  def find_movie
    @movie = Movie.find(params[:id])
    authorize @movie
  end

  def movie_params
    params.require(:movie).permit(:title, :country, :actors, :released, :poster, :poster, :poster_cache)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_movie.html.erb
<div class="container" id="partial-container">
  <div class="row">
    <div class="col-xs-4">
      <div class="movie-info">
        <div class="movie-poster">
          <%= image_tag "#{movie.imdb_poster ? movie.imdb_poster : movie.poster }", class: "movie-poster"  %>
        </div>
        <div class="grey-background-transparent padding-top-20">
          <div class="movie-title">
            <p>
              Rating of the movie: <%= movie.rating.to_f %> <i class="fa fa-star red-star" aria-hidden="true"> </i> out of <%= pluralize movie.reviews.size, 'review'  %>
            </p>
          </div>

          <div class="movie-info-box">
            <% movie.info_small.values.compact.each do |value| %>

            <span>
              <%= value + " |" %>
            </span>
            <% end %>
            <br>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-8">
      <% if review %>
      <div class= "card grey-background-transparent card-outline-primary mb-3 text-center">
        <div class= "card-header">
          <h3>
            <%= review.title %>
          </h3>
        </div>
        <div class="card-block">
          <div class="card-text">
            <blockquote class="card-blockquote">
              <p>
                <%= raw review.content %>
              </p>
              <footer>
                <cite>
                  Review's rating of the movie: <%= review.rating.to_f / 2 %> <i class="fa fa-star" style="color: green;" aria-hidden="true"> </i>
                  <br>
                  <%= review.created_at.strftime('%A, %d %b %Y %l:%M %p') %>
                  <br>
                   by <%= review.user.profile ? review.user.profile.username : review.user.email %>
                </cite>
              </footer>
            </blockquote>
          </div>
        </div>

        <%= render 'review_ratings/review_rating', review: review, movie: movie, review_rating: review_rating unless review.user == current_user %>
        <div class="card-btns">
          <% if current_user %>
          <% if policy(review).update? %>
          <%= link_to ' - Edit review', edit_movie_review_path(movie, review), class: "btn vegan-btn fa fa-eraser"  %>
          <% end %>
          <% if policy(review).destroy? %>
          <%= link_to 'Delete', movie_review_path(movie, review), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn vegan-btn" %>
          <% end %>
          <%= link_to 'Add a review', new_movie_review_path(movie), class: "btn vegan-btn" %>
          <% end %>
          <% if movie.times_reviewed > 1 %>
            <%= link_to 'More reviews', movie_path(movie), class: "btn vegan-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <% unless review.artwork.url.nil? || review.artwork.url == ""  %>
      <div class="background-value" data-hidden="linear-gradient(27deg, #D3D0CD 10%, rgba(150,150,150,0.7) 41%, rgba(  0,0,0,0.25) 100%), url(<%= review.artwork.url %>)">
      </div>
    <% else %>
      <div class="background-value" data-hidden="">
      </div>
    <% end %>

    <% else %>

    <p style="padding: 100px;">
      No reviews yet! <br>
      Be the first to leave one <%= link_to 'Leave a review', new_movie_review_path(movie), class: "btn vegan-btn"  %>
    </p>
    <% end %>
  </div>
</div>

app/views/movies/custom_new.html.erb
<div class="container">
  <div class="row">
    <div class="new-movie-select">
      <div class="col-xs-12">

        <h3>
          Add a custom movie
        </h3>

        <%= form_for @movie, :url => { :action => "custom_create" }, :html => { :method => "post" } do |f| %>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.text_field :title, placeholder: "Movie title", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-xs-12 text-center">
            <!-- TODO: Change format date field to dd-mm-yyyy -->
            <%= f.label :released, "When was the movie released? Only contemporary movies allowed!"%>
            <%= f.date_field :released, class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.text_field :actors, placeholder: "Add some of the cast here", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.text_field :genre, placeholder: "Which genre?", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.text_field :runtime, placeholder: "How many minutes?", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12">
            <span class="btn btn-success fileinput-button">
              <span>Add a poster</span>
              <%= f.file_field :poster, class: "text-center", id: 'artwork-input' %>
              <%=  f.hidden_field :poster_cache %>
            </span>
            <span id="selected-artwork"></span>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12">
            <%= f.text_field :imdb_poster, placeholder: "Or add a url, this one will get precedence if you do both!", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.text_field :country, placeholder: "From which country is the movie?", class: "form-control input-lg edit-input" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 text-center">
            <%= f.submit :Next, class: 'btn vegan-btn' %>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h4>Change Movie title and Vegan Critic Rating</h4>

<%= form_for(@movie) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :rating %>
<%= f.select :rating, [1,2,3,4,5] %>




<%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<%= render 'shared/archivenavbar'  %>
<section class='selector container-background' id='<%= @active %>'
<% if @review %>
<% unless @review.artwork.url.nil? || @review.artwork.url == ""  %>
  style="background: linear-gradient(27deg, #D3D0CD 10%, rgba(150,150,150,0.7) 41%, rgba(  0,0,0,0.25) 100%), url(<%= @review.artwork.url %>); background-size: cover;"
<% end %>
<% end %>
>
    <div class="container-fluid">
      <div class="row padding-top-20">

       <%= render 'shared/scrollbox', movies: @movies  %>

       <div class="col-xs-6 hidden-xs">
        <div class="review-index">
          <div class="content-review-index">
            <%= render 'movie', movie: @movie, review: @review, user: @user, review_rating: @review_rating %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/movies/new.html.erb
<section class='selector' id='review'>

  <div class="container">
    <div class="row">
      <div class="new-movie-select">
        <div class="col-xs-12 text-center">
          <h4>Which movie would you like to review?</h4>

          <%= form_for(@movie) do |f| %>

          <%= f.text_area :title, class: "form-control input-lg edit-input" %>
          <div class="row">
            <div class="col-xs-12 text-center">
              <%= f.submit :Next, class: "btn vegan-btn" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/movies/newest.html.erb
<section id='newest' class='selector'>
<div class="container">
 <div class="row">
   <% @newest_reviews.each do |review| %>
   <div class="col-xs-12 ">
    <div class="card">
      <div class="text-center">
        <h3>
          <%= review.movie.title %>
        </h3>
        <p>
         by <%= review.user.profile ? review.user.profile.username : review.user.email %>
        </p>
        <h5>
        <strong>
        <%= review.title  %>
          </strong>
        </h5>
        <div class="card-content">
          <p>
            <%=raw review.content %>
          </p>
          <br>
          <div class="fa fa-star"></div> <%= review.rating.to_f / 2  %>
          <br>
          <%= review.created_at.strftime('%A, %d %b %Y %l:%M %p') %>
        </div>
        <div class="card-btns">
          <%= link_to "See more", movie_review_path(review.movie, review), class: "btn vegan-btn" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>
</section>

app/views/movies/pending.html.erb
<section class='selector' id='pending'>
  <div class="container">
    <div class="row">
      <div class="pending-reviews text-center">
        <h2>
          Dear God among men, there are <%= @pending_reviews.size  %> reviews pending your approval.
        </h2>
      </div>
    </div>
    <div class="row">
     <% @pending_reviews.each do |review| %>
     <div class="col-xs-12">
      <div class="card">
        <div class="text-center">
          <h2>
            <%= review.movie.title %>
          </h2>
          <h4>
            <%= review.title %>,
          </h4>
          <%= review.rating.to_f / 2 %>
          <p>
            by <%= review.user.username   %>
            <br>
            <%= review.created_at.strftime('%A, %d %b %Y %l:%M %p') %>
          </p>
          <div class="card-content">
            <p>
              <%=raw review.content %>
            </p>
          </div>
          <div class="approve-btn">
            <%= link_to 'I Approve!', movies_pending_approve_path(review), class: "btn vegan-btn"  %>
            <%= link_to 'Hell no', movie_review_path(review.movie, review), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn vegan-btn" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</section>

app/views/movies/results.html.erb
  <h3 class="text-center">
    We've found <%= pluralize @movies.size, 'result' %> matching your query
  </h3>
</div>
<div class="container">
<div class="results">
 <div class="row">
   <% @movies.each do |movie| %>
   <div class="col-xs-12 col-sm-6">
    <div class="card">
      <div class="text-center">
        <h3>
          <%= movie.title %>
        </h3>
        <p>
        </p>
        <div class="card-content">
          <p>
            <%= movie.plot%>
          </p>
          <br>
          Rating: <%= movie.rating %>
          <br>
          <%= movie.created_at.strftime('%A, %d %b %Y %l:%M %p') %>
        </div>
        <div class="card-btns">
          <%= link_to "See more", movie_path(movie), class: "btn vegan-btn" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/movies/select.html.erb
<div class="container">
  <div class="row">
  <div class="col-sm-6 col-xs-12">

      <h1>
        Would you like to review the following movie?
      </h1>
      <div class="choose-buttons">
        <%= link_to 'Correct Movie', new_movie_review_path(movie_id: @movie), class: 'btn vegan-btn' %>
        <%= link_to 'Add a custom movie to review', movies_custom_new_path(movie_id: @movie), class: 'btn vegan-btn' %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12" style="margin-top: 20px">
      <div class="movie-info">
        <div class="movie-title">
          <h1>
            <%= @movie.title  %>
          </h1>
          <p>
            <%= @movie.plot  %>
          </p>
        </div>

        <div class="movie-info-box">
          <%= @movie.awards  %>
          <br>
          <%= @movie.actors %>
          <br>
          <%= @movie.runtime  %>
          <br>
          <%= @movie.genre  %>
          <div class="movie-poster">
            <%= image_tag "#{@movie.imdb_poster ? @movie.imdb_poster : @movie.poster }", class: "movie-poster"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<% if @movie.reviews.empty? %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <%= link_to 'Add a review', new_movie_review_path(@movie), class: "btn vegan-btn" %>
    </div>
  </div>
</div>
<% end %>

<% @reviews.each_with_index do |review, i| %>

  <% if i == 0 %>
    <div class="next-method current-element">
      <%= render 'reviews/review', review: review, i: i %>
    </div>

  <% else  %>

    <div class="next-method hidden">
      <%= render 'reviews/review', review: review, i: i %>
    </div>

  <% end %>
<% end %>

app/views/movies/show.js.erb
var data = "<%= j render 'movie', movie: @movie, review: @review, user: @user, review_rating: @review_rating %>"
$('.content-review-index').html(data);
$('.container-background').css('background-size', 'cover');
var background_url = $(".background-value").attr('data-hidden');
$('.container-background').css('background-image', background_url);
starRater();