config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  ActiveAdmin.routes(self)
  devise_for :users

    get '/movies/:id/partial', to: 'movies#partial'
    get '/movies/newest', to: 'movies#newest'
    get '/movies/highrated', to: 'movies#highrated'
    get '/movies/pending', to: 'movies#pending'
    get '/movies/pending/approve', to: 'reviews#approve'
    get '/home', to: 'home#home'
    get "/movies/#{Time.now.year}", to: 'movies#top10'
    get '/movies/alphabetical', to: 'movies#alphabetical'
    get '/movies/rated', to: 'movies#rated'
    get '/movies/most-reviewed', to: 'movies#most_reviewed'
    get '/results', to: 'movies#results'
    get '/movies/custom_new', to: 'movies#custom_new'
    post '/movies/custom_create', to: 'movies#custom_create'
    get '/thankyou', to: 'home#thankyou'
    get '/select', to: 'movies#select'

    resources :profiles

    resources :movies do
      resources :reviews do
        resources :review_ratings, only: [:create, :new, :edit, :update]
      end
    end
  root to: 'movies#newest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_archivenavbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to t(".top_call_to_action", default: " - Best rated"), movies_rated_path, id: 'rated', class: "navbar-wagon-item navbar-wagon-button btn far fa-star" %>
    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: " - Newest"), movies_path, id: 'newest-b', class: "navbar-wagon-item navbar-wagon-button btn far fa-calendar-alt" %>
    <%= link_to t(".top_call_to_action", default: " - Most reviewed"), movies_most_reviewed_path, id: 'most_reviewed', class: "navbar-wagon-item navbar-wagon-button btn far fa-comments" %>
  </div>

    <form accept-charset="UTF-8" method='get' action='/results' class="navbar-wagon-search">
    <input type="text" class="navbar-wagon-search-input" name="title" placeholder="Search reviews">
    <button type="submit" class="navbar-wagon-search-btn">
      <i class="fa fa-search"></i>
    </button>
  </form>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-sort dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/movies/rated"> Best Rated</a></li>
        <li><a href="/movies"> Newest</a></li>
        <li ><a href="/movies/most-reviewed"> Most Reviewed</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_buttons.html.erb
<div class="home-btns">
  <div class="col-xs-4">
    <%= link_to "What's new?", movies_newest_path, class: "btn btn-home vegan-btn" %>
  </div>
  <div class="col-xs-4">
    <%= link_to "#{Time.now.year} Top 10",eval("movies_#{Time.now.year}_path"), class: "btn btn-home vegan-btn" %>
  </div>
  <div class="col-xs-4">
    <%= link_to "Archive", movies_path, class: "btn btn-home vegan-btn" %>
  </div>
  <div class="col-xs-12">
    <%= link_to "Review", new_movie_path, class: "btn btn-home vegan-btn", style: "background-color: #a1c45a; color: rgb(15,15,15);" %>
  </div>
</div>

app/views/shared/_contact.html.erb
<a type="button" class="navbar-wagon-item navbar-wagon-button btn" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Contact</a>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">What's up?</h3>
        <button type="button" class="close" style="margin-top: -30px;" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="https://formspree.io/info@veganmoviecritic.com"
        method="POST">
        <input type="email" class="form-control" name="_replyto" placeholder="Your e-mail">
        <input type="text" class="form-control form-control-lg" name="name" style="margin-top: 3px; height: 200px;">
        <input type="submit" class="btn vegan-btn" value="Send">
      </form>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/user_navbar' %>
 <div class="navbar-wagon">
  <div class="vmr-logo">
    <%= link_to home_path, class: "vmr-logo" do %>
    <img src="<%= image_path("vegancriticlogo.png")  %>" alt="" style="height: 75px; z-index: 1; position: absolute; top: 35px; left: 0;">
    <% end %>
  </div>
  <!-- Logo -->

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to movies_newest_path, id: 'newest', class: "navbar-wagon-item navbar-wagon-button btn" do %>
      <i class="far fa-newspaper"></i>
      <%= t(".top_call_to_action", default: " - What's new") %>
    <% end %>
    <%= link_to eval("movies_#{Time.now.year}_path"), id: 'top10', class: "navbar-wagon-item navbar-wagon-button btn" do %>
      <i class="fas fa-trophy"></i>
      <%= t(".top_call_to_action", default: " - Top 10") %>
    <% end %>
    <%= link_to movies_path, id: 'archive', class: "navbar-wagon-item navbar-wagon-button btn " do %>
      <i class="fas fa-archive"></i>
      <%= t(".top_call_to_action", default: " - Archive") %>
    <% end %>
    <%= link_to new_movie_path, id: 'review', class: "navbar-wagon-item navbar-wagon-button btn" do %>
      <i class="fas fa-pencil-alt"></i>
      <%= t(".top_call_to_action", default: " - Add review") %>
    <% end %>
    <% if current_user.try(:admin) %>
      <%= link_to movies_pending_path, id: 'pending', class: "navbar-wagon-item navbar-wagon-button btn" do %>
        <i class="fa fa-hourglass-start"></i>
        <%= t(".top_call_to_action", default: " - Pending #{Review.where(approved: false).size}") %>
      <% end %>
    <% end %>
  <%= render 'shared/contact' %>

    <!-- Button (call-to-action) -->
    <!-- Different navigation if login or not -->
    <!-- Profile picture and dropdown -->
    <% if false #current_user %>
    <!-- Notification -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-user dropdown-toggle" data-toggle="dropdown" hidden></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li>
          <%= link_to (current_user.profile ? profiles_path(current_user.profile) : new_profile_path ), class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-user"> </i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <% if current_user.admin %>
          <%= link_to "/admin", class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-lock"></i>
          <% end %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% end %>

</div>


<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg" style="display: flex;">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="/movies/newest">What's new</a></li>
      <li><a href="/movies/<%= Time.now.year %>">Top 10</a></li>
      <li><a href="/movies">Archive</a></li>
      <li><a href="/movies/new"> Add A Review! </a></li>
    </ul>
  </div>
  <% if false #current_user %>
  <!-- Notification -->
  <div class="dropdown" style="margin: 60%;">
    <i class="fa fa-user dropdown-toggle" data-toggle="dropdown" ></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
     <li>
      <%= link_to (current_user.profile ? profiles_path(current_user.profile) : new_profile_path ), class: "navbar-wagon-item navbar-wagon-link" do %>
      <i class="fa fa-user"> </i> <%= t(".profile", default: "Profile") %>
      <% end %>
    </li>
    <li>
      <% if current_user.admin %>
      <%= link_to "/admin", class: "navbar-wagon-item navbar-wagon-link" do %>
      <i class="fa fa-lock"></i>
      <% end %>
      <% end %>
    </li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>
    </li>
  </ul>
</div>
<% end %>
</div>

</div>

app/views/shared/_scrollbox.html.erb
<div class="visible-xs-block xs-12">
  <div class="scrollbox-small">
    <div class="list">
      <% movies.each do |movie| %>
        <%= link_to "#{movie.title}", movie_path(movie), class: "list-item" %>
      <% end %>
    </div>
   </div>
 </div>

  <div class="col-sm-2 hidden-xs">
    <div class="scrollbox">
      <div class="list">
        <% movies.each_with_index do |movie, index| %>
         <%= link_to "#{movie.title}", movie_path(movie), remote: true, class: "list-item #{'active' if index == 0}" %>
       <% end %>
     </div>
   </div>
 </div>

app/views/shared/_star-rating.html.erb
<%= simple_form_for [@movie, @review, @review_rating], input_html: { class: 'stars-submit' }, remote: true do %>
  <fieldset class="rating">
    <input class="star-rating review-rater" type="radio" id="star5" name="review_rating[rating]" value="10" hidden-value= "<%= @user.id %>" />
    <label class ="full review-rater" for="star5" title="Awesome - 5 stars" hidden-value="<%= @user.id  %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star4half" name="review_rating[rating]" value="9" hidden-value= "<%= @user.id  %>"/>
    <label class="half review-rater" for="star4half" title="Pretty good - 4.5 stars" hidden-value= "<%= @user.id  %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star4" name="review_rating[rating]" value="8" hidden-value= "<%= @user.id  %>"/>
    <label class = "full review-rater" for="star4" title="Pretty good - 4 stars" hidden-value= "<%= @user.id  %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star3half" name="review_rating[rating]" value="7" hidden-value= "<%= @user.id %>"/>
    <label class="half review-rater" for="star3half" title="Meh - 3.5 stars" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star3" name="review_rating[rating]" value="6" hidden-value= "<%= @user.id %>" />
    <label class = "full review-rater" for="star3" title="Meh - 3 stars" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star2half" name="review_rating[rating]" value="5" hidden-value= "<%= @user.id %>"/>
    <label class="half review-rater" for="star2half" title="Kinda bad - 2.5 stars" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star2" name="review_rating[rating]" value="4" hidden-value= "<%= @user.id %>" />
    <label class = "full review-rater" for="star2" title="Kinda bad - 2 stars" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star1half" name="review_rating[rating]" value="3" hidden-value= "<%= @user.id %>"/>
    <label class="half review-rater" for="star1half" title="Meh - 1.5 stars" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="star1" name="review_rating[rating]" value="2" hidden-value= "<%= @user.id %>"/>
    <label class = "full review-rater" for="star1" title="Sucks big time - 1 star" hidden-value= "<%= @user.id %>">
    </label>
    <input class="star-rating review-rater" type="radio" id="starhalf" name="review_rating[rating]" value="1" hidden-value= "<%= @user.id %>"/>
    <label class="half review-rater" for="starhalf" title="Sucks big time - 0.5 stars" hidden-value= "<%= @user.id %>">
    </label>
  </fieldset>
<% end %>

app/views/shared/_starrating-review-new.html.erb
<fieldset class="rating">
  <input class="star-rating review-rater" method="post" type="radio" id="star5" name="review[rating]" value="10" hidden-value= "<%= current_user.id %>" />
  <label class = "full review-rater" for="star5" title="Awesome - 5 stars" method="post" hidden-value= "<%= current_user.id  %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star4half" name="review[rating]" value="9" hidden-value= "<%= current_user.id  %>"/>
  <label class="half review-rater" for="star4half" title="Pretty good - 4.5 stars" hidden-value= "<%= current_user.id  %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star4" name="review[rating]" value="8" hidden-value= "<%= current_user.id  %>"/>
  <label class = "full review-rater" for="star4" title="Pretty good - 4 stars" hidden-value= "<%= current_user.id  %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star3half" name="review[rating]" value="7" hidden-value= "<%= current_user.id %>"/>
  <label class="half review-rater" for="star3half" title="Meh - 3.5 stars" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star3" name="review[rating]" value="6" hidden-value= "<%= current_user.id %>" />
  <label class = "full review-rater" for="star3" title="Meh - 3 stars" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star2half" name="review[rating]" value="5" hidden-value= "<%= current_user.id %>"/>
  <label class="half review-rater" for="star2half" title="Kinda bad - 2.5 stars" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star2" name="review[rating]" value="4" hidden-value= "<%= current_user.id %>" />
  <label class = "full review-rater" for="star2" title="Kinda bad - 2 stars" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star1half" name="review[rating]" value="3" hidden-value= "<%= current_user.id %>"/>
  <label class="half review-rater" for="star1half" title="Meh - 1.5 stars" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="star1" name="review[rating]" value="2" hidden-value= "<%= current_user.id %>"/>
  <label class = "full review-rater" for="star1" title="Sucks big time - 1 star" hidden-value= "<%= current_user.id %>">
  </label>
  <input class="star-rating review-rater" method="post" type="radio" id="starhalf" name="review[rating]" value="1" hidden-value= "<%= current_user.id %>"/>
  <label class="half review-rater" for="starhalf" title="Sucks big time - 0.5 stars" hidden-value= "<%= current_user.id %>">
  </label>
</fieldset>

app/views/shared/_user_navbar.html.erb
<div class="navbar-user">
  <div class="navbar-user-left">
  <%= image_tag 'broccoli.png', class: 'tiny-logo' %>
  </div>
  <div class="navbar-user-right">
  <% if current_user %>
    <p>
      <% username = current_user.profile.try(:username) %>
      Hello, <%= username ? username : current_user.email %>
    </p>
    <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>
  </div>
</div>